config/routes.rb
Rails.application.routes.draw do
  root 'equipment#list'

  get 'new'         => 'equipment/new'
  resources :equipment

end

app/models/equipment.rb
class Equipment < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/equipment_controller.rb
class EquipmentController < ApplicationController
  def new
    @equipment = Equipment.new
  end

  def show
    @equipment = Equipment.find(params[:id])
  end

  def edit
    @equipment = Equipment.find(params[:id])
  end

  def index
    @equipment = Equipment.paginate(page: params[:page])
  end

  def list

  end

  def destroy
    Equipment.find(params[:id]).destroy
    flash[:success] = "削除成功"
    redirect_to equipment_index_url
  end

  def create
    @equipment = Equipment.new(equipment_params)    # 実装は終わっていないことに注意!
    if @equipment.save
      redirect_to @equipment
    else
      render 'list'
    end
  end

  def update
    @equipment = Equipment.find(params[:id])
    if @equipment.update_attributes(equipment_params)
      flash[:success] = "更新成功"
      redirect_to @equipment
    else
      render 'edit'
    end
  end

  def equipment_params
    params.require(:equipment).permit(:name, :model_number, :start_date)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title = '')                     # メソッド定義とオプション引数
    base_title = "備品管理"  # 変数の代入
    if page_title.empty?                              # 論理値でテスト
      base_title                                      # 暗黙的な返り値
    else
      page_title + " | " + base_title                 # 文字列の結合
    end
  end

end

app/helpers/equipment_helper.rb
module EquipmentHelper
end

app/views/equipment/delete.html.erb
<h1>Equipment#delete</h1>
<p>Find me in app/views/equipment/delete.html.erb</p>

app/views/equipment/edit.html.erb
<% provide(:title, :name) %>
<h1>端末導入 情報更新</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@equipment) do |f| %>
      <%= f.label "端末名" %>
      <%= f.text_field :name %>

      <%= f.label "型番" %>
      <%= f.text_field :model_number %>

      <%= f.label "導入開始日" %>
      <%= f.text_field :start_date %>

      <%= f.submit "更新", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/equipment/index.html.erb
<% provide(:title, 'equipment') %>
<h1>全備品一覧</h1>

<%= will_paginate %>
<ul class="equipment">
  <table>
  <tr>
    <td>端末名</td>
    <td>型番</td>
    <td>導入日</td>
  </tr>
  <% @equipment.each do |equipment| %>
  <tr>
    <td><%= link_to equipment.name ,equipment%></td>
    <td><%= equipment.model_number %></td>
    <td><%= equipment.start_date %></td>
  </tr>
  <% end %>
  </table>
</ul>
<%= will_paginate %>

app/views/equipment/list.html.erb
<% provide(:title, 'TOP') %>
<h1>トップページ</h1>
<%= link_to "備品一覧" ,equipment_index_path %>

app/views/equipment/new.html.erb
<% provide(:title, '新規登録') %>
<h1>端末導入 新規登録</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@equipment) do |f| %>
      <%= f.label "端末名" %>
      <%= f.text_field :name %>

      <%= f.label "型番" %>
      <%= f.text_field :model_number %>

      <%= f.label "導入開始日" %>
      <%= f.text_field :start_date %>

      <%= f.submit "登録", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/equipment/show.html.erb
<% provide(:title, @equipment.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <table>
      <tr>
        <td>端末名</td>
        <td><%= @equipment.name %></td>
      </tr>
      <tr>
        <td>型番</td>
        <td><%= @equipment.model_number %></td>
      </tr>
      <tr>
        <td>導入日</td>
        <td><%= @equipment.start_date %></td>
      </tr>
    </table>
    <%= link_to "情報更新" ,edit_equipment_path %>
    <%= link_to "一覧ヘ戻る" ,equipment_index_path %>
    <%= link_to "削除", @equipment, method: :delete,data: { confirm: "削除を行いますがよろしいですか？" } %>
    </section>
  </aside>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "備品管理", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "備品一覧",  equipment_index_path %></li>
        <li><%= link_to "備品新規登録",  new_equipment_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>